//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machado_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_list
    {
        public int Id { get; set; }
        public Nullable<int> product_Id { get; set; }
        public Nullable<int> customer_Id { get; set; }
        public Nullable<System.DateTime> tbl_date { get; set; }
        public Nullable<decimal> tbl_price { get; set; }
        public Nullable<int> tbl_quantity { get; set; }
        public string tbl_status { get; set; }
    
        public virtual tbl_customer tbl_customer { get; set; }
        public virtual tbl_product tbl_product { get; set; }
    }
}
