//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machado_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_staff
    {
        public int Id { get; set; }
        public string tbl_fname { get; set; }
        public string tbl_mname { get; set; }
        public string tbl_lname { get; set; }
        public string tbl_email { get; set; }
        public string tbl_username { get; set; }
        public string tbl_password { get; set; }
    }
}
